### ISSUE TITLE
Use data attributes even when instantiating manually

### ISSUE THREAD

**Issue by nebulousGirl** [markusslima/jquery-filestyle#10]
I had set the label to use on the button using a data attribute, but I was instantiating manually using JavaScript

```html
<input type="file"  name="file" data-buttonText="Parcourir" />
```

```js
$('.Form input[type=file]').jfilestyle();
```

While browsing the code I saw that data attributes where only used with the automatic trigger (class jfilestyle), shouldn't the JavaScript call also make use of the data attributes if it was not passed as an option?

**Comment by markusslima** [comment]
You can use both options together. No problem
