### ISSUE TITLE
Any chance to get the file button activated when clicking the text field next to it?

### ISSUE THREAD

**Issue by bongobongo** [markusslima/jquery-filestyle#14]
Feature request this is:
It would be nice if it was possible to optionally set up the filestyle plugin so the file button is activated when clicking the text field next to the file button?

If anyone has a quick solution for this, please share it here.

**Comment by markusslima** [comment]
This feature has been questioned here. It is rejected by this fact, the text field can not receive click because it is disabled. Preventing the user type in the field which can cause malfunctions.

**Comment by bongobongo** [comment]
Okay.... But in Chrome, IE, Opera, Firefox and Safari I can click the textfield for the standard file input field, and trigger the "filebrowser". Is there any technical issues that makes it impossible to get the same behaviour for your excellent filestyle plugin? Is it not possible to make your text input readonly, and thereby make it impossible to enter text into it, but still make it responsive to a click, which then again trigger a click for the related button.

**Comment by markusslima** [comment]
I honestly do not see any good reason for this operation. I'm interface developer and usability expert. Of course a disabled field can not be clickable so much that it could cause some confusion, browsers can even do since both use the same engine. So if a browser does, everyone will have. But if you show me a point quite useful for this feature I will implement soon.

**Comment by bongobongo** [comment]
My only point is that in the normal file input the user can actually click the the textfield and trigger the filebrowser. Simply because of this standard behaviour (which I explained in my previous comment) I thought it would be a good idea to make filestyle work the same way. So instead of making the field disabled, I would prefer it to be readonly, and make it respond to a click. But that is my thought about this - others may have different opinion. So my point is to make  your filestyle behave similar to standard file input field.

One other thing I'm curious about is how I make the checkbox border get similar look as when you hover over it with the mouse - when you tab into the checkbox (giving it focus). Is this something I can easily do as it is now, or does it need som plugin change?
As it is now, when I tab into a checkbox field, it is not visible that the checkbox has focus, and thereby harder for the user to actually see that he can e.g. push the space-bar to check it. It would also be nice if it was possible to see when a checked checkbox has focus.

**Comment by bongobongo** [comment]
Just a small update:
I was not precise enough when describing the default behaviour of the file input type. 
When I tab into a standard file input field, both the button and the "text" field gets highlighted as it was one field. 

So to make filestyle work in the same manner as standard file input I suggest keeping the text input for the file field disabled as it is now, but making it work so a click above the area of the filestyle text input (the disabled one) trigger a button click (if the text field in filestyle is just changed to readonly, then the user will be able to tab into both the button and the text field separately - which is not nice, and also breaks with standard behaviour).

I'm not going to suggest how to implement this behaviour, but I'm quite sure it should be possible though, without to much work. But since the disabled text input is within the same div as the filestyle "button" for the textfield, is it not possible to detect a click whithin that div, even if the user is clicking on the text field within that div?

This DIV that is:
`<div class="jfilestyle jfilestyle-corner  jfilestyle-buttonbefore">`

**Comment by bongobongo** [comment]
I have now tried to add some code to make a click on the filestyle text-field, trigger a click on the filestyle button like this:

`$(document).ready(function() {
       $( ".jfilestyle-buttonbefore" ).click(function(event) {
		   if (event.target.nodeName == "INPUT"){
		   		var elSpan = $(event.target).parent().children('span')[0];
		                var elLabel = $(elSpan).children('label');
		   		$( elLabel ).click(); 	
		   }
      });
 });`

It checks if user has clicked within the DIV that contains both the filestyle "button" and text field.
Then it checks if an INPUT has been clicked within that DIV, if it has, then the user has clicked above the text field, and therefore try to activate the click event for the filestyle button. 

It works in IE 11 and Chrome (did not test any earlier versions).

Unfortunately it does not work in Firefox, Opera and Safari.

If someone knows how to make this work in Firefox, Opera and Safari, please show some example code here.

**Comment by markusslima** [comment]
I analyzed your idea and found it very cool. I will be implementing this feature soon. Thank you
