### ISSUE TITLE
Multiple file input fields

### ISSUE THREAD

**Issue by pixelanddot** [markusslima/jquery-filestyle#15]
Hi,

I'm using Ninja Forms and your plugin to style an input field. Screenshot attached.

All is well but we're using the "Allow Repeatable?" option which adds another input.

Ninja forms is adding the new field but the plugin isn't styling it. I've tried calling the plugin to restyle all :file inputs when you click on the button and it does do after you've added 2 more.

I think the issue is the all have the same ID so you can only then use one file chooser, not all of them.

Any thoughts on how this could be resolved?

Thanks,
Barney

![screen shot 2016-08-03 at 13 55 45](https://cloud.githubusercontent.com/assets/20817287/17367968/199c5b82-598a-11e6-9c1a-0fd464b6a185.png)

**Comment by balazscsintalan** [comment]
Hi,

I might be late, but I use multiple of these without a problem in a pretty big app, what I do is basically just call .jfilestyle with the options passed when I create the new element (and before its visible to the user)

I don't think they should have all the same ID-s, you can give each a different ID when you insert another input element. (Or no ID at all, and just use some other form of selector to find it?)

Also I'm not sure what Ninja forms is or how it works, but maybe the add function runs after the styling (if so try bumping it to the end of the queue with a setTimeout)?

Just a couple of ideas.

**Comment by denizdogan** [comment]
@markusslima Are you mass-closing the issues? Is this project dead? I had this problem today too.

**Comment by markusslima** [comment]
It's not a problem. Only one programmer initialization logic error. Probably all of you are using auto-upload. When you create new elements the automatic upload does not work for the new ones for obvious reasons. So, every time you create new elements, you must start jquery-filestyle using javascript in this created element. From lonje or projects is dead, analyze the commits. It was fully updated.
