### ISSUE TITLE
Upload, Replace Image/file and Delete Button

### ISSUE THREAD

**Issue by zanetinemanish** [markusslima/jquery-filestyle#8]
Is this possible that we can create three buttons and perform following three functions:-

1. Create upload button which would be used for upload files or image.
2. Create Replace Image/file which would be used for replace already uploaded file/image. 
3. Create Delete Button for deleting uploaded file/Image.

 If it is possible how can i use them.

**Comment by markusslima** [comment]
- Use the clear method to clear the field
- The override button is not necessary since when choosing a new file the former is replaced.
- The file and upload example is to download this new version.

Sorry about the delay in answering it but the project was stopped and decided to resume and update.

**Comment by zanetinemanish** [comment]
Thank you Markus Lima for giving me an important tips.
