### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by gtrdblt** [markusslima/jquery-filestyle#9]
Hi,

First, I'd like to thank you for your work that I'm currently using for a personnal project.

I have a question that you might be able to answer to : is it possible to append another button ? Indeed, I'd like to have a "load" button and a "reset" button.

Thank you for your help.

Sincerly,

Gautier

**Comment by markusslima** [comment]
In the project you find a test directory. In it there are examples with more buttons along with an example to clean. But you have to style the new button.
